### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by dten** [msierks/rustcube#3]
rustyline seems not to work on windows :disappointed:

**Comment by msierks** [comment]
Indeed, rustyline currently doesn't support windows. I'm hoping it will in the near future.

https://github.com/kkawakam/rustyline/issues/37

**Comment by dten** [comment]
Oh nice yes! Didn't even see there was a pull request in progress
https://github.com/kkawakam/rustyline/pull/42
I tried using that as the dependency and rustcube's tests passed now :+1: exciting

**Comment by msierks** [comment]
Me neither. Thanks for pointing that out.

I've updated the rustyline dependency to the git windows_support branch. I've also added AppVeyor support and the builds are passing.

**Comment by kkawakam** [comment]
Hey @msierks, just giving you a heads up  that I am going to merging the windows_support branch into master in rustyline.  It still only provides partial support on Windows (e.g., modifier keys don't work)

**Comment by msierks** [comment]
Thanks for letting me know. :)

**Comment by bachimusprime** [comment]
Since rustyline now supports Windows, can this issue be closed, please?

**Comment by msierks** [comment]
Yes, I don't see why not.
